baseurl = "http://hivinay.com"
languageCode = "en-us"
title = "Vinay Hiremath"
theme = "hyde-x"

[author]
	name = "Vinay Hiremath"

[params]
	theme = "theme-base-09"
	tagline = "I'm especially interested in science, technology, psychology, philosophy, and linguistics."
	github = "http://github.com/hivinay"
	linkedin = "http://linkedin.com/in/vinayahiremath"
	facebook = "http://facebook.com/vinay427"
	twitter = "http://twitter.com/vinay427"
